<a href="https://colab.research.google.com/github/19PA1A0244/AI---lab/blob/master/Experiment_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EXPERIMENT-1
1.NUMPY


i.Different ways to create Numpy arrays


In [ ]:
import numpy as np
a = np.array([3,6,9])  
print (a)

[3 6 9]


In [ ]:
a = np.array([[1, 2], [3, 4]]) 
print (a)

[[1 2]
 [3 4]]


ii.Add,remove,modify elements in an array.



In [ ]:
newArray = np.append(a,[44,36,48])
print(newArray)

[ 1  2  3  4 44 36 48]


In [ ]:
import numpy as np
l=np.array([4,6,9,3,7])
l=np.delete(l,4)
print(l)

[4 6 9 3]


In [ ]:
b=np.array([6,9,8,5,2,1])
b[b<2]=-1
print(b)

[ 6  9  8  5  2 -1]


iii.Arthimetic operations on Numpy array

In [ ]:
import numpy as np
k=np.random.random((6,6))
p=np.random.random((6,6))
sum=np.add(k,p)
diff=np.subtract(k,p)
prod=np.multiply(k,p)
quo=np.divide(k,p)
mod=np.mod(k,p)
pow=np.power(k,p)
print(sum)
print(diff)
print(prod)
print(quo)
print(mod)
print(pow)

[[1.40296832 0.85223334 0.52770034 1.47781158 0.2845088  1.51976508]
 [1.00380709 1.00632855 1.27236259 1.15092344 0.73509764 1.47485498]
 [1.07803492 0.930016   1.17345176 0.53593657 0.53062524 1.32543951]
 [1.0167267  1.67072737 0.14408865 0.70111496 1.02552279 1.55801432]
 [1.40605763 1.33103743 1.02675803 0.68620517 1.29757351 0.7776001 ]
 [1.00599213 0.03736252 1.05293533 1.02922625 1.07559959 0.87096344]]
[[-0.02448182  0.10260167  0.42654694  0.45801525  0.25749618 -0.40471507]
 [ 0.59144561 -0.72716525 -0.47318019 -0.3555756  -0.44514674  0.08712191]
 [-0.49497753  0.15349064  0.27474371  0.10042693 -0.26146527  0.66557886]
 [-0.73414566  0.32920157  0.03007948  0.50911839  0.51036179 -0.25861603]
 [ 0.11883542  0.61292275 -0.59201453  0.27316853 -0.46773458  0.09601261]
 [ 0.92465693 -0.01383082  0.08416459 -0.29361636  0.50628491 -0.13538081]]
[[4.91930188e-01 1.78943639e-01 2.41313400e-02 4.93537276e-01
  3.66024361e-03 5.36472901e-01]
 [1.64455188e-01 1.20981965e-01 3.48751

iv.Slicing and iterating of numpy arrays

Slicing


In [ ]:
import numpy as np
ar=np.array([9,8,7,1,2,3])
print(ar[2:6])

[7 1 2 3]


Iterating

In [ ]:
for i in ar:
  print(i)

9
8
7
1
2
3


v.Matrix operation on numpy arrays.

In [ ]:
import numpy as np
s=np.array([[6,9,10],[4,8,3]])
p=np.array([[2,7,16],[1,5,12]])
print(np.add(s,p))
print(np.subtract(s,p))
print(np.divide(s,p))

[[ 8 16 26]
 [ 5 13 15]]
[[ 4  2 -6]
 [ 3  3 -9]]
[[3.         1.28571429 0.625     ]
 [4.         1.6        0.25      ]]
